config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root 'samples#index'

  # ↓以前の設定 only: [:new, :create]
  resources :samples do
    resources :air_times, only: :create
    collection do
      get 'search'
    end
  end


  #独自アクション用

  #全てsample_idが必要なのでネストする
  resources :samples do
    #urlアクセスによる自動ロケ移動用
    get 'auto_move_ast' => 'samples#auto_move_ast'
    get 'auto_move_one_sty' => 'samples#auto_move_one_sty'
    #単品編集用
    patch 'update2' => 'samples#update2'

  end
  
  get 'rent_list' => 'samples#rent_list'

  #モード切替
  post 'mode' => 'users#mode'


  resources :users, only: [:edit, :update]

  #履歴用独自アクション
  get 'rireki' => 'resumes#rireki'



end

app/models/sample.rb
class Sample < ApplicationRecord
  has_many :resumes
  has_many :air_times

  def self.search(search)
    if search.to_s =~ /^[0-9]+$/
      Sample.where('申込番号 LIKE(?)',"%#{search}%")
    else
      Sample.where('販売商品名 LIKE(?)',"%#{search}%")
    end
  end

  #ロケーション内検索用
  def self.search2(search)
    Sample.where('ロケーション LIKE(?)',"%#{search}%")
  end


  with_options length:{ minimum: 10, message:'10桁ありません' }, format: { with: /\A\d{10}/,message: '半角数字のみ登録可' } do
    validates :基本コード
  end

  validates :サブコード, length:{ minimum: 3, message:'3桁ありません' }, format: { with: /\A\d{3}/, message: '半角数字のみ登録可' }

  validates :個別番号, length:{ minimum: 1, message:'入力必須' }, format: { with: /\A\d{1}/, message: '半角数字のみ登録可' }

  validates :申込番号, length:{ minimum: 6, message:'6桁ありません' }, format: { with: /\A\d{6}/, message: '半角数字のみ登録可' }

  validates :販売商品名, :ロケーション, presence: true

  validates :カテゴリー, length:{ minimum: 2, message:'2桁ありません' }, format: { with: /\A\d{2}/, message: '半角数字のみ登録可' }


end

app/controllers/samples_controller.rb
class SamplesController < ApplicationController
  before_action :set_sample, only: [:edit, :show]

  def new
    @sample = Sample.new
  end
  #サンプル登録
  def create
    @sample = Sample.new(sample_params)
    if @sample.save
      @sample.update(rent: "")
      #↓操作履歴保存用アクションへ
      redirect_to rireki_path(@sample.id, request.parameters)
      #↑パスでパラメーターを送る(@sample.id, request.parameters)      
    else
      flash[:already] = "入力内容に不備があります。"
      render :new
    end
  end

  def edit
  end
  #サンプル個別詳細＋履歴＋OA登録・表示
  def show
    #履歴表示用（新しい順に）
    @resumes = Resume.where(sample_id: @sample.id).order("created_at DESC")
    #air_time登録用
    @air_time = AirTime.new

    #air_time表示用
    no = @sample[:申込番号] #6桁の申込番号取得 
    sam_top = Sample.find_by(申込番号: no) #同品番の最初のみ取得

    #該当するsample_id のOA予定のみ取得
    @air_times = AirTime.where(sample_id: sam_top[:id]).order("date DESC").order("sort_t")
    #日付は新しいのが上・同じ日付なら時間が早い順
  end
  
  #url貸出返却用
  def update
    @sample = Sample.find(params[:id])
    @old_loc = @sample.ロケーション#旧ロケ取得
    if @sample.update(ロケーション: params[:sample][:ロケーション])
      @sample.update(rent: "" )
      set_resume#履歴用

      flash[:already] = "返却が正常に完了しました。"
      render :done_move_one
    else
      flash[:already] = "ロケーション情報を入力して下さい"
      render :done_move_one
    end
  end
  
  #通常サンプル単品編集用※履歴保存未設定
  def update2
    sample = Sample.find(params[:sample_id]) 
    if sample.update(sample_params)
      redirect_to edit_sample_path(sample.id), notice: '正常に変更されました。'
    else
      redirect_to edit_sample_path(sample.id), notice: '入力内容が正しくありません。'
    end
  end
  
  #サンプル検索
  def search
    #ロケーション内検索用
    if params[:ロケーション]
      @samples = Sample.search2(params[:ロケーション])
      @keyword = (params[:ロケーション])
      flash[:all_sample_in_loc] = "ロケーション内の全サンプル検索です"#1
    #申込番号、商品名検索用
    else
      @samples = Sample.search(params[:keyword])
      @keyword = (params[:keyword])
      flash[:all_sample_in_loc] = "" #viewに#1のメッセージが出るにを防止
    end
  end


#ここから独自アクション（自動ロケーション更新機能）

  #同品番、同時変更 (移動先 = 所属/モード次第)
  def auto_move_ast
    if current_user[:group] == "Stylist" ||
       current_user[:group] == "Cast" ||
       current_user[:group] == "Still Image" ||
       current_user[:group] == "Promotion"
       #何もしない（ロケ移動できない）
       #flash[:already] = "権限がありません。（スタジオ移動のコードです）"
       redirect_to root_path, notice: "権限がありません。ST移動用コードです"

    else
      @sample = Sample.find(params[:sample_id]) 
      #3000/samples/id/auto_move_astでレコード指定
      no = @sample[:申込番号] #[]を使ってカラムを指定 
      @products = Sample.where(申込番号: no) #同品番を取得
      
      @products.each do |pro|
        if pro[:ロケーション] == "Stylist" ||
           pro[:ロケーション] == "Cast" ||
           pro[:ロケーション] == "Still Image" ||
           pro[:ロケーション] == "Promotion"
           #何もしない（ロケ移動できない）
           flash[:already] = "貸出中以外のサンプルを移動しました。"

        else
          # inv 入庫用
          if current_user.mode == "A-Bld-1F" ||
             current_user.mode == "A-Bld-2F" ||
             current_user.mode == "B-Bld-7F" ||
             current_user.mode == "INV-4F"

            old_loc = pro.ロケーション#旧ロケ取得

            pro.update(ロケーション: current_user[:mode])

            resume = Resume.new(
              user_id: current_user[:id],
              sample_id: pro.id,
              ロケーション旧: old_loc,#ロケ更新前に取得
              ロケーション新: pro.ロケーション,
              name: current_user[:name],
              group: current_user[:group] )    
              resume.save

            flash[:already] = "#{current_user[:mode]}へ移動しました"
          
          #ST 入庫
          else
            old_loc = pro.ロケーション#旧ロケ取得

            pro.update(ロケーション: current_user[:group] )

            resume = Resume.new(
              user_id: current_user[:id],
              sample_id: pro.id,
              ロケーション旧: old_loc,#ロケ更新前に取得
              ロケーション新: pro.ロケーション,
              name: current_user[:name],
              group: current_user[:group] )    
              resume.save


            flash[:already] = "ロケーションの移動が完了しました。"
          end

        end

      end
      render :done_move #記述は一つのみ
    end

  end


  #単品貸出 / pick用
  def auto_move_one_sty
    @sample = Sample.find(params[:sample_id]) 
    if @sample[:ロケーション] == "Stylist" ||
       @sample[:ロケーション] == "Cast" ||
       @sample[:ロケーション] == "Still Image" ||
       @sample[:ロケーション] == "Promotion"

      flash[:already] = "#{@sample.rent}がすでに貸出処理されています。"
      render :done_move_one

    #集荷モード用
    elsif current_user.mode == "A-Bld-1F" ||
          current_user.mode == "A-Bld-2F" ||
          current_user.mode == "B-Bld-7F" ||
          current_user.mode == "INV-4F"
   
      @old_loc = @sample.ロケーション#旧ロケ取得
      @sample.update(ロケーション: current_user[:mode] )
      
      set_resume#履歴用

      flash[:already] = "#{current_user[:mode]}へ移動しました"
      render :done_move_one

    #貸出処理用
    else 
      @old_loc = @sample.ロケーション#旧ロケ取得
      @sample.update(ロケーション: current_user[:group] )
      @sample.update(rent: current_user[:name] )
      #render plain: @sample[:ロケーション] #パラメーターをテキストで画面表示用

      set_resume#履歴用

      flash[:already] = "貸出処理が完了しました。"
      render :done_move_one
    end

  end


  #同品番複数移動結果表示
  def done_move
    @sample = Sample.find(params[:sample_id]) 
    no = @sample[:申込番号] 
    @products = Sample.where(申込番号: no) #同品番を全て取得
  end

  #単品移動結果表示
  def done_move_one
      @sample = Sample.find(params[:sample_id]) 
  end


  #貸出リスト
  def rent_list
    if current_user.group == "Inventory" ||
       current_user.group == "A-STUDIO" ||
       current_user.group == "C-STUDIO"

       @samples = Sample.where(rent: params[:rent])
       flash[:already] = "　#{params[:rent]}【貸出中一覧】"
    
    else
    #自分の貸出確認専用
    @samples = Sample.where(rent: current_user[:name]) 
    flash[:already] = "　#{current_user[:name]}【貸出中一覧】"
    end

  end


  private

  def sample_params
    params.require(:sample).permit(:基本コード, :サブコード, :個別番号, :申込番号, :販売商品名, :カテゴリー, :カラー, :ロケーション, :rent )
  end

  def set_sample
    @sample = Sample.find(params[:id]) 
  end

  def set_resume
    resume = Resume.new(
      user_id: current_user[:id],
      sample_id: @sample.id,
      ロケーション旧: @old_loc,#ロケ更新前に取得
      ロケーション新: @sample.ロケーション,
      name: current_user[:name],
      group: current_user[:group] )    
      resume.save
  end


end

app/helpers/samples_helper.rb
module SamplesHelper
end

app/views/samples/done_move.html.erb
<p class="fin"><%= flash[:already] %>
<p class="p03">*スタジオ移動専用のタグをスキャンすると<br>同じ申込番号のサンプルの別のサブ（別カラー）をまとめて移動します。<br>実際の現場でもOA前の準備ではこのように移動します。</p>

<div class="search-list">
  <% @products.each do |prod| %>
    <p class="sea-res">
    <%= prod.基本コード %>-
    <%= prod.サブコード %> #
    <%= prod.個別番号 %>　　　ロケ：
    <%= prod.ロケーション %>

    </p>

    <p class="sea-res2">
    <%= link_to "#{prod.販売商品名}", sample_path(prod.id),method: :get, class:'sample-btn' %>
    　　　<%= prod.カラー %>
    </p>

    <% if prod.rent != "(該当無し)" &&
          prod.rent != "" %>
      <p class="fin">　貸出中：<%= prod.rent %></p>
    <% end %>


  <% end %>
</div>

app/views/samples/done_move_one.html.erb
<p class="fin"><%= flash[:already] %></p>
<!--p class="p02">貸出中：<%= @sample.rent %></p-->
<p class="p03">*↑はタグをスキャンしたあとの処理内容のメッセージです。<br>貸出したサンプルを返却する時は同じタグを再度スキャンします。</p>

<div class="search-list">
    <p class="sea-res">

    <%= @sample.基本コード %>-
    <%= @sample.サブコード %> #
    <%= @sample.個別番号 %>　　　ロケ：
    <%= @sample.ロケーション %>

    </p>
    <p class="p03">*NFC / QR タグをスキャンした対象のサンプル</p>

    <p class="sea-res2">
    <%= link_to "#{@sample.販売商品名}", sample_path(@sample.id),method: :get, class:'sample-btn' %>
    <%= @sample.カラー %>
    </p>

    <%= link_to "#{@sample.申込番号} の一覧を確認" , search_samples_path(keyword:@sample.申込番号 ), class:'btn01' %>

  <%# 貸出本人/INV社員だけが返却できるようにする %>
  <% if current_user.name == @sample.rent ||
        current_user.group == "Inventory" %>

    <%=form_with model: @sample , local: true do |f|%>
        
        <div class='done-form'>
          <%= f.label :バーコードで返却する場合はこちら %>
        </div>
        <div class='field-input'>
          <%= f.text_field :ロケーション, placeholder:'NFC/ QR / 直接入力' , maxlength:10, size:16, value:"" %>
        </div>
        <p class="p03">*文字列情報が入ったNFC / QR タグがあれば利用可</p>

        <%= f.submit "このロケへ返却", class:'btn01'%>

    <% end %>

    <!-- プルダウン返却 -->
        <!-- 同品番のあるロケをプルダウンで返却先に指定 -->
        <%=form_with model: @sample , local: true do |f|%>
        
          <div class='done-form'>
            <%= @sample.申込番号 %> <%= f.label :の他サブ保管先へ返却 %>
          </div>
          <div class='field-input'>
            <%= f.collection_select :ロケーション,
             Sample.where(申込番号: @sample.申込番号)
             .where.not(id: @sample.id )
             .where.not( ロケーション: "Still Image" )
             .where.not( ロケーション: "Cast" )
             .where.not( ロケーション: "Stylist" )
             .where.not( ロケーション: "Promotion" ), :ロケーション, :ロケーション %>
          </div>
          <p class="p03">*一つの申込番号（6桁）には複数のサブ（別カラーなど）があります。<br>通常、それらは同じロケーションで保管されます。<br>ここでは貸出されていない他のサブのあるロケが表示されます。</p>
          <%= f.submit "このロケへ返却", class:'btn01'%>

        <% end %>

  <% end %>

</div>

app/views/samples/edit.html.erb
<div class='new-sample'>

  <%=form_with model: @sample, url:'update2', local: true do |f|%>
    <div class='sample-form'>
      <p class="fin"><%= notice %></p><br>
      <p class="fin"><%= flash[:already] %>


      <%= link_to "#{@sample.申込番号} の一覧へ戻る" , search_samples_path(keyword:@sample.申込番号 ), class:'btn01' %>

      <h1>サンプル情報変更</h1>

      <div class=''>
        <%= f.label :基本コード, class: ''%>
      </div>
      <div class='field-input'>
        <%= f.text_field :基本コード, class: '', placeholder: '10桁',size: 16 , maxlength:10, autocomplete: "off" %>
      </div>

      <div class=''>
        <%= f.label :サブコード, class: ''%>
      </div>
      <div class='field-input'>
        <%= f.text_field :サブコード, class: '', placeholder: '3桁',size: 5 , maxlength:3 %>
      </div>

      <div class=''>
        <%= f.label :個別番号, class: ''%>
      </div>
      <div class='field-input'>
        <%= f.text_field :個別番号, class: '', placeholder: '2桁',size:3,maxlength:2 %>
      </div>

      <div class=''>
        <%= f.label :申込番号, class: ''%>
      </div>
      <div class='field-input'>
        <%= f.text_field :申込番号, class: '', placeholder: '6桁',size:12,maxlength:6 %>
      </div>

      <div class=''>
        <%= f.label :販売商品名, class: ''%>
      </div>
      <div class='field-input'>
        <%= f.text_field :販売商品名, class: '', placeholder: '販売商品名', size:16 %>
      </div>


      <div class=''>
        <%= f.label :カテゴリー番号, class: ''%>
      </div>
      <div class='field-input'>
        <%= f.text_field :カテゴリー, class: '', placeholder: '2桁',size:3,maxlength:2 %>
      </div>

      <div class=''>
        <%= f.label :カラー・サイズ等, class: ''%>
      </div>
      <div class='field-input'>
        <%= f.text_field :カラー, class: '', placeholder: 'なくても可', size:16%>
      </div>

      <div class=''>
        <%= f.label :ロケーション, class: ''%>
      </div>
      <div class='field-input'>
        <%= f.text_field :ロケーション, size:16 %>
      </div>

      <div class=''>
        <%= f.label :rent, class: ''%>
      </div>
      <div class='field-input'>
        <%= f.text_field :rent, size:16 %>
      </div>

        <%= f.submit "情報変更",class: 'btn01'%>
    </div>
    
  <% end %>
  <br>
  
</div>

app/views/samples/index.html.erb
  <div class="">
    <p class="fin">　<%= notice %></p>
    <p class="menu">共通メニュー</p>
    <% if current_user.group == "Cast" ||
          current_user.group == "Still Image" ||
          current_user.group == "Promotion" ||
          current_user.group == "Stylist" %>
      <p> <%= link_to "自分の貸出確認", rent_list_path, class: 'btn01' %> </p><br><br>
    <% else %>
      <%# 通常メニュー %>
      <div class="field-input">
        <p class="p04" >貸出リストを確認する</p>
        <%= form_with(url: rent_list_path, local: true, method: :get, class: "") do |f| %>
        <%= f.collection_select :rent, Sample.select(:rent).distinct.where.not(rent: ""), :rent, :rent %>

        <%= f.submit "検索", class: "search-btn" %>
        <p class="p03">*貸出中のサンプルがある場合<br>リスト内に貸出者名が表示されます。</p><br>
        <% end %>
      </div>
      <%# ロケーション内検索 %>
      <div class="field-input">
        <p class="p04" >ロケーション別・全サンプルリスト</p>

        <div class="search2">
          <%= form_with(url: search_samples_path, local: true, method: :get, class: "") do |f| %>
          <%= f.collection_select :ロケーション, Sample.select(:ロケーション).distinct, :ロケーション, :ロケーション %>
          <%= f.submit "検索", class: "search-btn" %>
          <% end %>
        </div>
        <p class="p03">*サンプルが保管されている<br>ロケーションのみ表示されます。</p><br>
      </div>
    <% end %>
  </div>

  <div class="">
    <p class="menu">Inventory専用メニュー</p>
    <% if current_user.group == "Inventory" %>
      <p><br><%= link_to "サンプル登録", new_sample_path, class: 'btn01' %></p>
      <p class="p03">*TV放送で販売する商品サンプルを登録。</p><br>
        <div class="field-input">
          <p class="p04" >入庫モード切替</p>
          <%= form_with url: "/mode", method: :post, id:"mode" do |f|%>
          <div class='mode-menu'>
          
            <div class='field-input'>
              <%= f.select :mode, ['A-Bld-1F','A-Bld-2F','B-Bld-7F','INV-4F'], { selected: current_user.mode } %>              
            </div>

            <div class="btn01" id="mode-btn">
              <%= f.submit "モード切替" %>
            </div>

            <div class="mode-now <%= current_user.mode %>" id="mode-now" >
              <p><%= current_user.mode %></p>
            </div>

          </div>
          <p class="p03">*ロケーションの移動先を設定。<br>ここで設定した内容がそのままロケーション名となります。<br>*A-Bld-1F = ビルAの1階</p>
          <% end %>
        </div>

    <% else %>
      <p class="p03">*現在ログイン中のユーザーは利用できません。<br>　部署が Inventory の社員専用のメニューです。</p>
    <% end %>

  </div>

app/views/samples/new.html.erb
<div class='new-sample'>
  <%=form_with(url: samples_path, model:@sample, local: true) do |f|%>
    <div class='sample-form'>
      <p class="fin"><%= notice %></p><br>
      <p class="p03">*項目名は実際に私の職場で使用しているものです。<br>適当な番号でも登録は可能です。<br>決まった「申込番号」を入力した場合は<br>詳細ページに自動で商品画像が表示されるようになります。</p><br>
      <h1>新規サンプル登録</h1>
      <p class="fin"><%= flash[:already] %></p>

      <div class=''>
        <%= f.label :基本コード, class: ''%>
        <p class="fin" ><%= @sample.errors.messages[:基本コード][0] %>
      </div>
      <div class='field-input'>
        <%= f.text_field :基本コード, class: '', autofocus: true, placeholder: '10桁',size: 12 , maxlength:10, autocomplete: "off" %>
      </div>

      <div class=''>
        <%= f.label :サブコード, class: ''%>
        <p class="fin" ><%= @sample.errors.messages[:サブコード][0] %>

      </div>
      <div class='field-input'>
        <%= f.text_field :サブコード, class: '', placeholder: '3桁',size: 4 , maxlength:3 %>
      </div>

      <div class=''>
        <%= f.label :個別番号, class: ''%>
        <p class="fin" ><%= @sample.errors.messages[:個別番号][0] %>
      </div>
      <div class='field-input'>
        <%= f.text_field :個別番号, class: '', placeholder: '2桁まで',size:3,maxlength:2 %>
      </div>

      <div class=''>
        <%= f.label :申込番号, class: ''%>
        <p class="fin" ><%= @sample.errors.messages[:申込番号][0] %>
      </div>
      <div class='field-input'>
        <%= f.text_field :申込番号, class: '', placeholder: '6桁',size:8,maxlength:6 %>
      </div>

      <div class=''>
        <%= f.label :販売商品名, class: ''%>
      </div>
      <div class='field-input'>
        <%= f.text_field :販売商品名, class: '', placeholder: '入力必須です', size:16 %>
      </div>


      <div class=''>
        <%= f.label :カテゴリー番号, class: ''%>
        <p class="fin" ><%= @sample.errors.messages[:カテゴリー][0] %>
      </div>
      <div class='field-input'>
        <%= f.text_field :カテゴリー, class: '', placeholder: '2桁',size:3,maxlength:2 %>
      </div>

      <div class=''>
        <%= f.label :カラー・サイズ等, class: ''%>
      </div>
      <div class='field-input'>
        <%= f.text_field :カラー, class: '', placeholder: 'なくても可', size:16%>
      </div>

      <div class=''>
        <%= f.label :ロケーション, class: ''%>
      </div>
      <div class='field-input'>
        <%= f.select :ロケーション, { '1ロケ': "11111111", '2ロケ': "22222222" }, { include_blank: 'どちらか選択' }, { class:'', required: true } %>
      </div>

        <%= f.submit "新規登録",class: 'btn01'%>
    </div>
    
  <% end %>
  
</div>

app/views/samples/rent_list.html.erb
<p class="p02"><%= flash[:already] %></p>
<p class="p03">*自分が貸出中のサンプルがあれば表示されます。</p>
<div class="search-list">
  <% @samples.each do |sam| %>
    <p class="sea-res">
    <%= sam.基本コード %>-
    <%= sam.サブコード %> #
    <%= sam.個別番号 %>　　　ロケ：
    <%= sam.ロケーション %>
    </p>

    <p class="sea-res2">
    <%= sam.販売商品名 %>　　　
    <%= sam.カラー %>
    </p>

    <%= link_to "#{sam.申込番号} の一覧を確認" , search_samples_path(keyword:sam.申込番号 ), class:'btn01' %>

  <% end %>
</div>

app/views/samples/search.html.erb
<div>
    <h2>検索結果</h2>
    <p class="p03">*Inventoryの社員のみ「情報変更」のメニューが出ます。<br>他の社員は詳細情報は確認できます。</p>
    <p class="fin"><%= flash[:all_sample_in_loc] %> </p>
    <p class="p02">　"<%= @keyword %>"で検索しています。</p>

    <div class="search-list">
      <% count = 0 %>
      <% @samples.each do |sample| %>
        <% count += 1 %>
        
        <p class="sea-res">
          <%= sample.基本コード %>-
          <%= sample.サブコード %> #
          <%= sample.個別番号 %>　　　ロケ：
          <%= sample.ロケーション %>
        </p>

        <div class="sea-res2">
          <div class="">
            <%= link_to "#{sample.販売商品名}", sample_path(sample.id),method: :get, class:'sample-btn' %>
            　　　<%= sample.カラー %>
          </div>

          <%# サンプル編集はインベントリー専用 %>
          <div class="">
            <% if current_user.group == "Inventory" %>
              <%= link_to '情報変更', edit_sample_path(sample.id),method: :get,class: 'btn01' %>
            <% end %>
          </div>     
    
        </div>
        
        <% if sample.rent != "" %>
          <p class="fin">　貸出中：<%= sample.rent %></p>
        <% end %>

      <% end %>
        <br><p><%= count %>件見つかりました。</p>
        
</div>

app/views/samples/show.html.erb
<div class="search-list">
  <p class="fin"><%= flash[:onair] %></p>
  <%# 基本情報 %>
  <div class="">
    <p class="menu" >サンプル個別詳細情報：<%= @sample.基本コード %></p>
    <p class="p03">*商品サンプルの詳細情報は<br>実際の現場ではかなり高い頻度で見られます。</p>
    <p class="p02">
    　<%= @sample.申込番号 %>
    -<%= @sample.サブコード %>
    #<%= @sample.個別番号 %>
    　<%= @sample.販売商品名 %>
    　ctg<%= @sample.カテゴリー %>
    </p>
    <p class="p02">
    　ロケ：<%= @sample.ロケーション %>
    　【<%= @sample.カラー %>】
    </p>
  </div>

  <%# menu1 商品画像 %>
  <div class="">
    <p class="menu" >サンプル画像 ※現在表示されているのは見本です</p>

    <img src="https://www.shopch.jp/img/prod/<%= @sample.申込番号[0,3] %>/<%= @sample.申込番号[3,3] %>/<%= @sample.申込番号 %>01E.jpg" alt="仮の写真" class="sample_img" onerror="this.style.display='none'">

    <img src="https://www.shopch.jp/img/prod/<%= @sample.申込番号[0,3] %>/<%= @sample.申込番号[3,3] %>/<%= @sample.申込番号 %>02E.jpg" alt="仮の写真" class="sample_img" onerror="this.style.display='none'">

    <img src="https://www.shopch.jp/img/prod/<%= @sample.申込番号[0,3] %>/<%= @sample.申込番号[3,3] %>/<%= @sample.申込番号 %>03E.jpg" alt="仮の写真" class="sample_img" onerror="this.style.display='none'">

    <img src="https://www.shopch.jp/img/prod/<%= @sample.申込番号[0,3] %>/<%= @sample.申込番号[3,3] %>/<%= @sample.申込番号 %>51E.jpg" alt="仮の写真" class="sample_img" onerror="this.style.display='none'">

    <img src="https://www.shopch.jp/img/prod/<%= @sample.申込番号[0,3] %>/<%= @sample.申込番号[3,3] %>/<%= @sample.申込番号 %>52E.jpg" alt="仮の写真" class="sample_img" onerror="this.style.display='none'">

    <img src="https://www.shopch.jp/img/prod/<%= @sample.申込番号[0,3] %>/<%= @sample.申込番号[3,3] %>/<%= @sample.申込番号 %>53E.jpg" alt="仮の写真" class="sample_img" onerror="this.style.display='none'">

    <img src="https://www.shopch.jp/img/prod/<%= @sample.申込番号[0,3] %>/<%= @sample.申込番号[3,3] %>/<%= @sample.申込番号 %>71E.jpg" alt="仮の写真" class="sample_img" onerror="this.style.display='none'">


  </div>

  <%# menu2 OA情報 %>
  <div class="">
    <%# menu2-1 OA予定表示 %>
    <div class="">
      <p class="menu" >OA予定・過去OA情報</p>
      <p class="p03">*TV放送で使う予定・使った記録です。<br>実際の現場でも秒単位で管理されています。</p>
      <% @air_times.each do |air_time| %>
        <% wd = ["日","月","火","水","木","金","土"] %>
        
        <p class="sea-res" >
          <%= air_time.date %>　
          [<%= wd[air_time.date.wday] %>]
        </p>

        <p class="sea-res2" >
          [S]<%= l air_time.start_t, format: :onlytime %>　
          <%# ↑↓locales>ja.yml内でformat設定 %>
          [E]<%= l air_time.end_t, format: :onlytime %>　
          <%# コントローラー内で合計air_time計算 %>
          [AT]<%= l air_time.onair_t, format: :onlytime %>
        </p>

      <% end %>
      <p class="p03">*部署がInventoryの社員は<br>この下にOA予定の登録フォームが表示されます。</p>

    </div>

    <%# menu2-2 OA予定登録 %>
    <div class="">
      <% if current_user.group == "Inventory" %>
        <p class="menu" >OA予定登録</p>
        <%= form_with(model: [@sample,@air_time], local: true) do |f| %>
        
        　OA日<%= f.date_field :date, :value => Time.now.strftime('%Y-%m-%d'), class:'air_time_form' %><br>
        　開始<%= f.time_select :start_t, include_seconds: true %><br>
        　終了<%= f.time_select :end_t, include_seconds: true %><br>
        　<%= f.submit "OA登録", class: 'air_time_form_btn' %>
        <p class="p03">*TV放送で使う予定を秒単位で登録。<br>放送時間 [AT] は自動で計算されます。</p>

        <% end %>
      <% end %>
    </div>
  </div>


  <%# menu3 ロケ移動履歴 %>
  <div class="">
    <p class="menu" >ロケーション移動履歴</p>
    <p class="p03">*社員がサンプルを移動した履歴です。<br>実際の現場でかなり高い頻度で見ます。<br>主に、サンプル所在が不明時の捜索に使用。</p>

    <% @resumes.each do |resume| %>
      
      <p class="sea-res">
      <%= resume.ロケーション旧 %> 　=>　
      <%= resume.ロケーション新 %>　
      <%= resume.name %>
      </p>

      <p class="sea-res2">
      <%# エル( l )メソッドで日本時刻 %>
      <%= l resume.created_at %>
      　部署：<%= resume.group %>
      </p>

    <% end %>
  </div>
</div>