config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root 'samples#index'

  # ↓以前の設定 only: [:new, :create]
  resources :samples do
    resources :air_times, only: :create
    collection do
      get 'search'
    end
  end


  #独自アクション用

  #全てsample_idが必要なのでネストする
  resources :samples do
    #urlアクセスによる自動ロケ移動用
    get 'auto_move_ast' => 'samples#auto_move_ast'
    get 'auto_move_one_sty' => 'samples#auto_move_one_sty'
    #単品編集用
    patch 'update2' => 'samples#update2'

  end
  
  get 'rent_list' => 'samples#rent_list'

  #モード切替
  post 'mode' => 'users#mode'


  resources :users, only: [:edit, :update]

  #履歴用独自アクション
  get 'rireki' => 'resumes#rireki'



end

app/views/layouts/_exp-content.html.erb
      <div class="exp-menu">
        <ul class="exp-lists">
          <li class="exp-menu-list" id="exp-menu1">1,アプリ概要</li>
          <li class="exp-menu-list" id="exp-menu2">2,課題解決</li>
          <li class="exp-menu-list" id="exp-menu3">3,利用準備</li>
          <li class="exp-menu-list" id="exp-menu4">4,user情報</li>
          <li class="exp-menu-list" id="exp-menu5">5,撮影チーム</li>
          <li class="exp-menu-list" id="exp-menu6">6,キャスター</li>
          <li class="exp-menu-list" id="exp-menu7">7,操作履歴</li>
          <li class="exp-menu-list" id="exp-menu8">8,Aスタジオ</li>
          <li class="exp-menu-list" id="exp-menu9">9.Inventory</li>
          <li class="exp-menu-list" id="exp-menu10">10,OA登録</li>
          <li class="exp-menu-list" id="exp-menu11">見本QR4</li>
          <li class="exp-menu-list" id="exp-menu12">見本QR5</li>
          <li class="exp-menu-list" id="exp-menu13">見本QR6</li>
          <li class="exp-menu-list" id="exp-menu14">見本QR7</li>
          <li class="exp-menu-list" id="exp-menu15">最後に</li>
        </ul>
      </div>
      <div class="exp-inside" id="exp-inside">
        <%# 1,アプリ概要 %>
        <div class="inside-menu1" id="inside-menu1" >
          <p class="p05">アプリ概要</p>
          <p class="p06">【目的】<br>TVショッピング業界向け　商品サンプルロケーション管理</p><br>
          <p class="p06">【想定する利用企業】<br>このアプリは私の現在の職場（自社の放送局を持つTV通販会社）での利用を想定して作りました。<br>同じTV通販業界・一般のTV局・社内の商品サンプルを頻繁に移動する可能性のある企業で利用が出来ます<br></p><br>
          <p class="p06">【利用概要】<br>PCのブラウザで表示は可能ですが、このアプリはスマホでの利用を想定して作っております。<br>viewはスマホ向けに作っております。スマホでの利用方法を含めてこの説明メニューを順にご覧ください。<br>この説明メニューはPC/タブレット等で表示されます。その為、PC＋スマホを1〜2台ご用意頂くと体験しやすいです。</p><br>ご不明な点はメールでお気軽にお問い合わせ下さい。<%= mail_to 'kyuu5988@yahoo.co.jp' %>
        </div>
        <%# 2,課題解決 %>
        <div class="inside-menu2" id="inside-menu2" >
          <p class="p05">課題解決</p>
          <p class="p06">現職場の社内システムの不便なところを社員より実際に聞き取り、その内容を改善してこのアプリを作りました。</p>
          <p class="p06">【現行社内システム】<br>①ロケーションの移動処理に赤外線ターミナルを利用。３〜４アクション必要で手間が掛かります。<br>②現在は3つのシステムを使用しており、必要な機能ごとにそのアプリを立ち上げる必要がある<br>③殆どの昨日はPCでしか操作出来ない。（作業現場の近くにPCが配置出来ない<br>④現状は高額なハンディターミナルを購入またはレンタルする必要がある（ハンディ20万×20台程）</p>
          <p class="p05">【このアプリを利用した場合】</p>
          <p class="p06">①スマホのNFC / QR の読取機能を利用して１〜２アクションで同じ操作を行うことが出来る。<br>②利用頻度の高い複数機能を統一（ロケーション移動・TVオンエア予定参照・社員の操作履歴照会）<br>③スマホで全ての機能が利用できるので、狭い現場でも作業がしやすいです。<br>④端末は古いスマホでも動作するのでコストが低いです。（社内ローカル運用前提なのでsim契約不要）</p><br>
        </div>
        <%# 3,利用準備 %>
        <div class="inside-menu3" id="inside-menu3" >
          <p class="p05">利用準備</p>
          <p class="p06">①QRコードを読み取れるスマホをご用意下さい。<br><br>②標準のカメラアプリで読み込めると思いますが、読み込めない場合は無料でダウンロードできる「クルクル - QRコードリーダー」がお勧めです。(ストアで"クルクル"と検索すると候補に出ます。) ※設定で「開く前に確認」を off にして頂くとこの後がスムーズです。<br>③次のQRコードを読み取るとスマホブラウザでこのアプリのトップが表示されます。（ログインページ）</p>
          <p><img src="https://test.samoant.com/wms_3_qr/hewms_3_top.png" alt="top_page" class="qr_img"></p>
          <p class="p06">（海外サーバーの為、表示までかなり時間が掛かります。）<br>Basic認証 ユーザー:kyuu5988 / PW:hideo</p>
        </div>
        <%# 4,user情報 %>
        <div class="inside-menu4" id="inside-menu4" >
          <p class="p05">user情報</p>
          <p class="p06">ログインするuser（社員）は部署の種類があり、それにより機能が異なります。<br>ご自身で作成して頂くことも可能です。<br><br>【登録済user】（Email /  概要）password = 12341234<br>i@i / "山田太郎"インベントリーチーム（全機能利用可）<br>c@c / TV放送出演する"キャスター二郎"（貸出返却可）<br>s@s / 静止画撮影チーム”カメラの三郎”（貸出返却可）<br>ast@ast / Aスタジオ担当専用（スタジオ移動可能）"AD役"<br>cst@cst / Cスタジオ担当専用（スタジオ移動可能）"AD役"<br><br>【新規登録】<br>所属部署を「Inventory」にして頂くと全ての機能が利用出来ます。<br>「各STUDIO」なら現場ADとなり、それ以外はそれぞれのチーム社員となります。</p>
          <p class="p06">（各チームの社員が貸出を行う機能は共通です。貸出の際に記録されるロケーションが変わります。）<br><br>（次のメニューで撮影チームの貸出を試してみて下さい。）</p>
        </div>
        <%# 5,撮影チーム %>
        <div class="inside-menu5" id="inside-menu5" >
          <p class="p05">s@s 静止画撮影チーム</p>
          <p class="p06">【QRコードのスキャン】商品サンプル貸出処理<br>実際には商品サンプルにQRやNFCタグが貼ってあります。<br>※事前に現在のロケーションを検索で確認して見て下さい。<br>スキャンしたら処理終了です。画面操作は必要ありません。</p>
          <p><img src="https://test.samoant.com/wms_3_qr/he666613-002one.png" alt="ネックレス" class="qr_img"></p>
          <p class="p06">・「666613」で検索すると一覧を確認出来ます。<br>リストの上から5番目が該当品です。666613-002 #2<br>（もう一度、このQRをスキャンすると返却が出来ます。）<br>【別の社員が借りようとした場合】<br>すでに貸出したサンプルは貸し出すことは出来ません。<br>c@cなど、別の社員IDで試してみてください。<br>すでに貸出者がいると"貸出されている"と出ます。</p>
        </div>
        <%# 6,キャスター %>
        <div class="inside-menu6" id="inside-menu6" >
          <p class="p05">c@c キャスター（放送に出演して商品紹介をする方です。）</p>
          <p class="p06">一つ前のメニューとは違う、別のサンプルを借りてみます。(別のチームでも貸出可能)<br>【QRコードのスキャン】<br>先程と同じく、スキャンするとその時点で貸出処理終了です。１アクションです。</p>
          <p><img src="https://test.samoant.com/wms_3_qr/he672076-001one.png" alt="ダイソン" class="qr_img"></p>
          <p class="p06">・「672076」で検索すると一覧を確認出来ます。<br>リストの上から3番目が該当品です。672076-001 #3<br>（もう一度、このQRをスキャンすると返却が出来ます。）<br>【返却】画面上に返却メニューが出ます。一番下のプルダウンから選んで返却するのが簡単です。処理は一瞬ですので、繰り返し行わないように注意して下さい。</p>
        </div>
        <%# 7,操作履歴 %>
        <div class="inside-menu7" id="inside-menu7" >
          <p class="p05">操作履歴(ロケ移動時に自動保存)</p>
          <p class="p06">「撮影チーム」「キャスター」のページで何回かロケーション移動を行いました。その際の履歴が残っています。<br>両方のページで出ているサンプルの番号で商品検索します。<br>該当サンプルの詳細ページの一番下には今行った操作の履歴が残っています。<br>（※番号の一部や商品名の一部のみでも検索可）<br>
          <p class="p05">【検索してみるサンプル】</p>
          <p class="p06">「672076」ダイソン掃除機<br>リストの上から3番目が該当品です。672076-001 #3<br>「666613」真珠ネックレス<br>リストの上から5番目が該当品です。666613-002 #2<br><br>履歴はずっと残りますので、他の方の操作履歴も残っています。（実際のシステムでも数年分の記録を保存します。）<br><br>※他の方が貸出体験をする時の為に返却処理をして頂くと助かります。<br><br>次はスタジオにいるADになって商品サンプルをまとめて移動してみます。</p>
        </div>
        <%# 8,Aスタジオ %>
        <div class="inside-menu8" id="inside-menu8" >
          <p class="p05">ast@ast Aスタジオ担当専用アカウント</p>
          <p class="p06">放送で使う商品サンプルを準備する部署です。<br>毎日数百点〜千点程移動があります。<br>【QRコードのスキャン】ast@ast でログインしましょう。<br>今までと違うのはスキャンすると同じ申込番号（6桁）の物はまとめて移動処理をすることが出来ます。 スキャンのみで処理終了、操作不要です。</p>
          <p><img src="https://test.samoant.com/wms_3_qr/he664839all.png" alt="デニムパンツ" class="qr_img"></p>
          <p class="p06">・「664839」で検索すると一覧を確認出来ます。<br>スキャン後は全てのサンプルが一括でスタジオロケに変わります。（貸出中を除く）<br>【返却】スタジオ担当は直接返却処理をしません。ここで次の、Inventoryチームの出番です。</p>
        </div>
        <%# 9,Inventory %>
        <div class="inside-menu9" id="inside-menu9" >
          <p class="p05">i@i 　Inventoryチーム（サンプル管理部署）</p>
          <p class="p06">先ほどスタジオへ移動したサンプルを戻してみましょう。<br>【QRコードのスキャン】userは i@iでログイン<br>・TOPページで入庫先(入庫ロケ)を変更出来ます。</p>
          <p><img src="https://test.samoant.com/wms_3_qr/he664839all.png" alt="デニムパンツ" class="qr_img"></p>
          <p class="p06">・「664839」で検索すると一覧を確認出来ます。<br>リストの全てが該当品です。<br>今度はスキャン後に全てのサンプルが一括でTOPページで設定したロケに変わります。（貸出中を除く）<br>【貸出中強制返却】キャスターの方(c@c)等がサンプルを借りて返却処理をしていない場合は強制的に返却可能です。<br>このままのuserで「キャスター」メニューのQRをスキャンすると返却メニューが出ます。（先にキャストで借りる）</p>
        </div>
        <%# 10,OA登録 %>
        <div class="inside-menu10" id="inside-menu10" >
          <p class="p05">OA予定登録（Inventoryチーム専用機能）</p>
          <p class="p06">TVのオンエアで使用する予定を登録できる機能です。<br>空欄で検索（品番指定でも可）して適当なサンプルの詳細画面に移ります。<br>i@iなど、Inventoryチームでログインする必要があります。<br><br>詳細ページの中間地点ほどに登録フォームが現れます。（試しに登録してみて下さい。）</p>
          <p class="p06">【登録後の表示順】（現職場システムに合わせました。）<br>・日にちは新しい順番が上。<br>・同じ日にちの場合は時間が早いものが上。<br><br>過去のOA履歴はずっと残る仕様です。<br><br>以上が大まかな機能説明です。いくつか見本のQRコードを用意したので動作確認にご利用下さい。<br>この画面を通してですとQRコードでのみとなりますが、実際に私が目の前で実演する場合はNFCタグを用意して動作確認出来ます。（仕組みは同じです。）</p>
        </div>
        <%# 見本QR4 %>
        <div class="inside-menu11" id="inside-menu11" >
          <p class="p05">見本4 単品貸出用QR シチズン腕時計</p>
          <p class="p06">【対象user】<br>c@c （キャスター）<br>s@s（撮影チーム）<br>（ Stylist / Promotion 部署所属でも可）</p>
          <p><img src="https://test.samoant.com/wms_3_qr/he636470-001one.png" alt="腕時計" class="qr_img"></p>
          <p class="p06">Inventoryチームであれば強制的に返却処理が可能<br>また、Inventoryチームのみ、トップページで入庫モードを変更出来ます。（入庫先変更機能）</p>
        </div>
        <%# 見本QR5 %>
        <div class="inside-menu12" id="inside-menu12" >
          <p class="p05">見本5 単品貸出用QR シャツA</p>
          <p class="p06">【対象user】<br>c@c （キャスター）<br>s@s（撮影チーム）<br>（ Stylist / Promotion 部署所属でも可）</p>
          <p><img src="https://test.samoant.com/wms_3_qr/he675780-006one.png" alt="シャツ" class="qr_img"></p>
          <p class="p06">Inventoryチームであれば強制的に返却処理が可能<br>また、Inventoryチームのみ、トップページで入庫モードを変更出来ます。（入庫先変更機能）</p>
        </div>
        <%# 見本QR6 %>
        <div class="inside-menu13" id="inside-menu13" >
          <p class="p05">見本6 複数スタジオ移動用QR ハンドバッグ</p>
          <p class="p06">【対象user】<br>ast@ast （Aスタジオ担当）<br>cst@cst（Cスタジオ担当）<br>（ 他部署では移動出来ないとメッセージが出ます。）</p>
          <p><img src="https://test.samoant.com/wms_3_qr/he668518all.png" alt="バッグ" class="qr_img"></p>
          <p class="p06">Inventoryチームがスキャンした場合は自分たちのフロアに戻す処理となります。<br>トップページで入庫モードを変更出来ます。（入庫先変更機能）</p>
        </div>
        <%# 見本QR7 %>
        <div class="inside-menu14" id="inside-menu14" >
          <p class="p05">見本7 複数スタジオ移動用QR レザージャケット</p>
          <p class="p06">【対象user】<br>ast@ast （Aスタジオ担当）<br>cst@cst（Cスタジオ担当）<br>（ 他部署では移動出来ないとメッセージが出ます。）</p>
          <p><img src="https://test.samoant.com/wms_3_qr/he674287all.png" alt="ジャケット" class="qr_img"></p>
          <p class="p06">Inventoryチームがスキャンした場合は自分たちのフロアに戻す処理となります。<br>トップページで入庫モードを変更出来ます。（入庫先変更機能）</p>
        </div>
        <%# 最後に %>
        <div class="inside-menu15" id="inside-menu15" >
          <p class="p05">最後に</p>
          <p class="p06">ここまで説明を読んで頂きありがとうございます。<br><br>・herokuへデプロイ後も定期的にチェックは致しますが、不具合が有る可能性もありますのでご了承下さい。<br>・実際のローカル環境で動作をお見せすることはいつでも可能です。メールでご連絡下さい。<br>・このアプリは社内のシステム向けですので大量のDBが存在するのが前提です。（現在の職場ではおよそ3万件前後のDBがありそれをこのようなシステムで管理しています。）<br>・heroku上ではあまり多くのDBを用意出来ないので少しアプリの便利さが伝わり難いかもしれません。<br>・実際にこの完成したアプリは現在の職場の社員には好評です。（採用は社内のルール上難しい）<br>・このアプリは2020年7月にプログラミングを初めて勉強して9月頃には基本の大枠は完成させていました。（仕事とスクールの合間に作った物です。）<br>・現在は2つ目の自作アプリを作成中です。<br>・まだまだ色々学びたいです。興味を持って頂けたら嬉しいです！</p>
        </div>



      </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>wms_3</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <!-- responsive / reset css / web font -->
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <%# <link rel="stylesheet" type="text/css" href="http://yui.yahooapis.com/3.18.1/build/cssreset/cssreset-min.css"> %>
    <link href="https://fonts.googleapis.com/css?family=Noto+Sans+JP:400,700,900&display=swap" rel="stylesheet">

    <!-- responsive / reset css / web font -->
    
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

<header>
  <p class="p01">wms_3 mobile <%= link_to 'TOP', '/',class:'fot-btn' %></p>

  <div class="search">
    <%= form_with(url: search_samples_path, local: true, method: :get, class: "") do |f| %>
    <%= f.text_field :keyword, placeholder: "申込番号6桁", class:"search-input", autocomplete: "off", maxlength:10 %>
    <%= f.submit "検索", class: "search-btn" %>
    <% end %>
  </div>

  <div class="">
      <p class="p01">無入力で全在庫検索 <span class="p03">*印はapp紹介の為の追加説明文です。</span></p>
  </div>

  <%# exp about wms_3 %>
    <div class="exp-board" id="exp-board">
      <p class="">企業様向け説明メニュー(クリックでON/OFF)</p>
      <p class="">*利用方法の説明です。左上から順番にご覧下さい。</p>
    </div>

    <div class="exp-content" id="exp-content">
      <%= render partial: "layouts/exp-content" %>
    </div>
  <%# exp about wms_3 %>

</header>

    <%= yield %>

<footer>

  <div class="fot-menu">
    <p class="p03">*印はapp紹介の為の追加説明文です。</p>
    <div class="fot-btn">
      <%= link_to 'TOP', '/' %>
    </div>
    
    <% if user_signed_in? %>
    <div class="fot-btn">
      <%= link_to edit_user_path(current_user) do %>
      ログイン中 : <%= current_user.name %> / <%= current_user.group %>
      <% end %>
    </div>

    <div class="fot-btn">
      <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'btn'%>
    </div>
    <% end %>

    <p class="p01">Minami Hideo wms_3 mobile</p>
  </div>

</footer>


  </body>
</html>